version: '2'
services:
        web:
                build: ./web
                depends_on:
                        - app
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./data/html:/var/www/html
                        - ./webconf/default.conf:/etc/nginx/conf.d/default.conf
        app:
                image: wordpress:5.3.2-php7.4-fpm-alpine
                depends_on:
                        - db
                volumes:
                        - ./data/html:/var/www/html

        db:
                image: mysql:5.7.29
                ports:
                        - "3306:3306"
                volumes:
                        - db-data:/var/lib/mysql
volumes:
        db-data:
